site_name: Ontology Development Kit (ODK)

theme:
  name: material
  icon:
    edit: material/pencil 
  features:
    - content.action.edit

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

nav:
  - Home: index.md
  - ODK User Docs:
    - ODK Schema: project-schema.md
    - ODK Schema Options: schema-options.md
    - Using the Development Snapshot: ODKDevelopmentSnapshot.md
    - Frequently used ODK commands: FrequentlyUsedODKCommands.md
  
repo_url: https://github.com/INCATools/ontology-development-kit/
site_url: https://incatools.github.io/ontology-development-kit/
edit_uri: edit/master/docs/
