id: mp
title: "Mammalian Phenotype Ontology"
github_org: obophenotype
repo: mammalian-phenotype-ontology
report_fail_on: none
use_dosdps: TRUE
dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
allow_equivalents: assert-only
namespaces: 
  - http://purl.obolibrary.org/obo/MP_
  - http://purl.obolibrary.org/obo/mp[#]
  - http://purl.obolibrary.org/obo/mp-edit[#]
  - http://purl.obolibrary.org/obo/mp/
  - http://purl.obolibrary.org/obo/mp-edit/
release_artefacts: 
  - base
  - simple-non-classified
  - full
primary_release: simple-non-classified
export_formats:
  - owl
  - obo
  - json
import_group:
  products: 
    - id: nbo
      mirror_from: http://purl.obolibrary.org/obo/nbo/nbo-base.owl
    - id: pr
      mirror_from: http://purl.obolibrary.org/obo/pr.owl.gz
    - id: go
    - id: uberon 
    - id: ro
    - id: chebi
      mirror_from: http://purl.obolibrary.org/obo/chebi.owl.gz
    - id: pato
    - id: cl
      mirror_from: http://purl.obolibrary.org/obo/cl/cl-base.owl
    - id: mpath
robot_java_args: '-Xmx8G'
allow_equivalents: asserted-only