id: wbphenotype
title: "C. elegans Phenotype Ontology"
github_org: obophenotype
repo: c-elegans-phenotype-ontology
report_fail_on: none
use_dosdps: TRUE
dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
namespaces: 
  - http://purl.obolibrary.org/obo/WBPhenotype_
release_artefacts: 
  - base
  - simple-non-classified
  - full
  - simple
primary_release: full
export_formats:
  - owl
  - obo
  - json
import_group:
  products: 
    - id: go
    - id: wbbt
    - id: wbls 
    - id: ro
    - id: chebi
      mirror_from: http://purl.obolibrary.org/obo/chebi.owl.gz
    - id: pato
    - id: cl
    - id: iao
    - id: bfo
components:
  products:
    - filename: wbphenotype-equivalent-axioms-subq.owl
robot_java_args: '-Xmx8G'
allow_equivalents: asserted-only
