id: zp
title: "Zebrafish Phenotype Ontology"
github_org: obophenotype
repo: zebrafish-phenotype-ontology
report_fail_on: none
use_dosdps: TRUE
export_formats:
  - owl
  - obo
import_group:
  products:
    - id: zfa
    - id: go
    - id: uberon 
    - id: ro
    - id: chebi
      mirror_from: http://purl.obolibrary.org/obo/chebi.owl.gz
    - id: bspo
    - id: pato
    - id: mpath
    - id: bfo
pattern_pipelines_group:
  products:
    - id: manual
      dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
    - id: anatomy
      dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
    - id: zfin
      dosdp_tools_options: "--obo-prefixes=true --restrict-axioms-to=logical"
    - id: labels
      dosdp_tools_options: "--obo-prefixes=true"
robot_java_args: '-Xmx8G'
allow_equivalents: asserted-only   