name: Build the ODK images and run the tests

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**.md'
      - 'CITATION.cff'
      - 'LICENSE'
      - 'docs/**'
      - 'mkdocs.yml'
      - 'INSTALL.sh'
      - 'env.sh'
      - 'odk.sh'
      - 'odk2.sh'
      - 'seed-via-docker-131.sh'
      - '*.bat'
      - 'upgrade*sh'
      - '.github/workflows/build-multiarch.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create dummy Git user name
        run: git config --global user.name Alice
      - name: Create dummy Git user email
        run: git config --global user.email alice@example.org
      - name: Build the images
        run: make build
      - name: Export the ODKFull image to an archiv
        run: docker image save -o ${{ runner.temp }}/odkfull.tar
      - name: Upload exported archive
        uses: actions/upload-artifact@v4
        with:
          name: odkfull-image
          path: ${{ runner.temp }}/odkfull.tar

  test_workflows:
    strategy:
      matrix:
        os: [unbuntu-latest, macos-15-intel, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: build_image
    steps:
      - name: Download the ODKFull archive
        uses: actions/download-artifact@v4
        with:
          name: odkfull-image
          path: ${{ runner.temp }}
      - name: Load the ODKFull image
        run: docker load --input ${{ runner.temp }}/odkfull.tar
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Create dummy Git user name
        run: git config --global user.name Alice
      - name: Create dummy Git user email
        run: git config --global user.email alice@example.org
      - name: Run the tests (GNU/Linux and macOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: make test-no-build
      - name: Run the tests (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: make test CMD=seed-via-docker.bat ODK_IMAGE=odkfull
