name: Build and publish the multi-arch ODK images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up the QEMU static binaries
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Create a builder instance
        run: docker buildx create --use
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the images
        run: make publish-multiarch
