name: Build and publish the multi-arch ODK images

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: 'Type of image to build'
        required: true
        default: 'release'
        type: choice
        options:
          - release
          - snapshot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          persist-credentials: false
      - name: Set up the QEMU static binaries
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push the release images
        if: ${{ inputs.buildType == 'release' }}
        run: make publish-multiarch
      - name: Build and push the snapshot images
        if: ${{ inputs.buildType == 'snapshot' }}
        run: make publish-multiarch-dev
