name: Build the ODK images and run the tests

on:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
    - name: Build the images
      run: make build
    - name: Run the tests
      run: make tests
